name: Pull Request

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-node@v3.6.0
      with:
        cache: yarn
        check-latest: true
    - run: yarn
    - run: yarn lint --no-fix

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
    - uses: actions/setup-node@v3.6.0
      with:
        cache: yarn
        check-latest: true
    - run: yarn
    - run: yarn build

  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
    - uses: actions/setup-node@v3.6.0
      with:
        cache: yarn
        check-latest: true
    - run: yarn
    - run: yarn build:frame
    - run: yarn test
    - uses: coverallsapp/github-action@v1.2.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test LTS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
        - 16
        - 18
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
    - uses: actions/setup-node@v3.6.0
      with:
        cache: yarn
        node-version: ${{ matrix.node }}
    - run: yarn
    - run: yarn build:frame
    - run: yarn test
